#ifndef __ASSET_STORE_H__
#define __ASSET_STORE_H__

typedef enum
{
	TEXTURE_TANK_IMAGE,
	TEXTURE_TRUCK_IMAGE,
	TEXTURE_CHOPPER_IMAGE,
	TEXTURE_TILEMAP_IMAGE,
	TEXTURE_RADAR_IMAGE,
	TEXTURE_BULLET_IMAGE,
	TEXTURE_TREE_IMAGE,
	TEXTURE_COUNT,
	TEXTURE_NONE
} TextureIdEnum;

#endif